sunday = Day.create(name: "Sunday")
monday = Day.create(name: "Monday")
tuesday = Day.create(name: "Tuesday")
wednesday = Day.create(name: "Wednesday")
thursday = Day.create(name: "Thursday")
friday = Day.create(name: "Friday")
saturday = Day.create(name: "Saturday")

user_1 = User.create(username: "Fiona234", email: "Fefifofum@mail", password: "Shrek")
user_2 = User.create(username: "Beetlejuice", email: "stripedsuit@mail", password: "Lydia")

read = Task.create(name: "read")
bills = Task.create(name: "pay bills")
exercise = Task.create(name: "exercise")
clean = Task.create(name: "clean")
grocery = Task.create(name: "go to grocery")
errands = Task.create(name: "run errands")
mom = Task.create(name: "call mom")
